services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Autorise les requêtes provenant de ton navigateur vers l'EC2
      - CORS_ALLOW_ORIGINS=http://localhost,http://localhost:5173,http://localhost:80,http://15.224.107.108
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # L'adresse que ton navigateur va appeler pour joindre le backend FastAPI
        - VITE_API_BASE_URL=http://15.224.107.108:8000
    container_name: erp-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
