from enum import Enum


class MovementType(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"

    TRANSFER_IN = "TRANSFER_IN"
    TRANSFER_OUT = "TRANSFER_OUT"

    ADJUSTMENT = "ADJUSTMENT"
    
    # Nouveaux types pour le Stock Projet
    ENTRY_GENERAL = "ENTRY_GENERAL"
    ENTRY_PROJECT = "ENTRY_PROJECT"
    TRANSFER_TO_PROJECT = "TRANSFER_TO_PROJECT"
    PROJECT_CONSUMPTION = "PROJECT_CONSUMPTION"
