"""Add PaymentMilestone and ProjectBudget partner_id

Revision ID: 02a7ba2f576d
Revises: 265fb9e2808f
Create Date: 2026-08-12 15:36:59.932041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a7ba2f576d'
down_revision: Union[str, Sequence[str], None] = '265fb9e2808f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_payment_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PAID', name='paymentmilestonestatus'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_payment_milestones_id'), 'project_payment_milestones', ['id'], unique=False)
    op.add_column('project_budgets', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_budgets', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_budgets', type_='foreignkey')
    op.drop_column('project_budgets', 'partner_id')
    op.drop_index(op.f('ix_project_payment_milestones_id'), table_name='project_payment_milestones')
    op.drop_table('project_payment_milestones')
    # ### end Alembic commands ###
