"""add_daily_reports_and_photos

Revision ID: 179f9b021ef0
Revises: b300c84a7a33
Create Date: 2026-08-12 13:16:36.367879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179f9b021ef0'
down_revision: Union[str, Sequence[str], None] = 'b300c84a7a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Text(), nullable=False),
    sa.Column('issues_encountered', sa.Text(), nullable=True),
    sa.Column('plan_next_day', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', name='reportstatus', create_type=False), nullable=True),
    sa.Column('photos_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'report_date', name='uq_employee_project_day')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.add_column('weekly_reports', sa.Column('photos_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_reports', 'photos_urls')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
