"""Add Quality KPI models

Revision ID: 3b1e7b3f2973
Revises: 474ec6124158
Create Date: 2026-07-31 12:05:13.346732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1e7b3f2973'
down_revision: Union[str, Sequence[str], None] = '474ec6124158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_kpi_processus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_kpi_processus_id'), 'quality_kpi_processus', ['id'], unique=False)
    op.create_index(op.f('ix_quality_kpi_processus_name'), 'quality_kpi_processus', ['name'], unique=True)
    op.create_table('quality_kpi_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['processus_id'], ['quality_kpi_processus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_kpi_indicators_id'), 'quality_kpi_indicators', ['id'], unique=False)
    op.create_table('quality_kpi_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('value_raw', sa.String(length=100), nullable=True),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['quality_kpi_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'year', 'month', name='uix_kpi_value_indicator_year_month')
    )
    op.create_index(op.f('ix_quality_kpi_values_id'), 'quality_kpi_values', ['id'], unique=False)
    op.create_table('quality_kpi_yearly_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('target_raw', sa.String(length=100), nullable=True),
    sa.Column('target_numeric', sa.Float(), nullable=True),
    sa.Column('target_numeric_max', sa.Float(), nullable=True),
    sa.Column('operator', sa.Enum('GTE', 'LTE', 'BETWEEN', 'EQ', name='kpioperator'), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['quality_kpi_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'year', name='uix_kpi_target_indicator_year')
    )
    op.create_index(op.f('ix_quality_kpi_yearly_targets_id'), 'quality_kpi_yearly_targets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_kpi_yearly_targets_id'), table_name='quality_kpi_yearly_targets')
    op.drop_table('quality_kpi_yearly_targets')
    op.drop_index(op.f('ix_quality_kpi_values_id'), table_name='quality_kpi_values')
    op.drop_table('quality_kpi_values')
    op.drop_index(op.f('ix_quality_kpi_indicators_id'), table_name='quality_kpi_indicators')
    op.drop_table('quality_kpi_indicators')
    op.drop_index(op.f('ix_quality_kpi_processus_name'), table_name='quality_kpi_processus')
    op.drop_index(op.f('ix_quality_kpi_processus_id'), table_name='quality_kpi_processus')
    op.drop_table('quality_kpi_processus')
    # ### end Alembic commands ###
