"""add_assigned_user_to_review

Revision ID: 474ec6124158
Revises: ab6457a3dadf
Create Date: 2026-07-31 11:45:16.316247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474ec6124158'
down_revision: Union[str, Sequence[str], None] = 'ab6457a3dadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quality_document_role_reviews', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quality_document_role_reviews', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quality_document_role_reviews', type_='foreignkey')
    op.drop_column('quality_document_role_reviews', 'assigned_user_id')
    # ### end Alembic commands ###
