"""Add interoperability relationships

Revision ID: 4a519456d593
Revises: f326669cc67b
Create Date: 2026-07-29 12:52:42.253188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a519456d593'
down_revision: Union[str, Sequence[str], None] = 'f326669cc67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_expenses', sa.Column('purchase_order_line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_expenses', 'purchase_order_lines', ['purchase_order_line_id'], ['id'], ondelete='SET NULL')
    op.add_column('project_stock_reservations', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_stock_reservations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_order_lines', sa.Column('budget_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_order_lines', 'project_budgets', ['budget_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order_lines', type_='foreignkey')
    op.drop_column('purchase_order_lines', 'budget_id')
    op.drop_constraint(None, 'project_stock_reservations', type_='foreignkey')
    op.drop_column('project_stock_reservations', 'task_id')
    op.drop_constraint(None, 'project_expenses', type_='foreignkey')
    op.drop_column('project_expenses', 'purchase_order_line_id')
    # ### end Alembic commands ###
