"""Add caisse validators

Revision ID: 5e90dce47cb3
Revises: b7c8d9e0f1a2
Create Date: 2026-08-25 11:57:41.404116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e90dce47cb3'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caisse_vouchers', sa.Column('demandeur_id', sa.Integer(), nullable=True))
    op.add_column('caisse_vouchers', sa.Column('validator_cg_id', sa.Integer(), nullable=True))
    op.add_column('caisse_vouchers', sa.Column('validator_dga_id', sa.Integer(), nullable=True))
    op.add_column('caisse_vouchers', sa.Column('validator_dg_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'caisse_vouchers', 'users', ['validator_cg_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'caisse_vouchers', 'users', ['validator_dg_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'caisse_vouchers', 'users', ['demandeur_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'caisse_vouchers', 'users', ['validator_dga_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_employee_documents_user_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_messages_room_created'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_index(op.f('ix_requests_project_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_requester_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status_type'), table_name='requests')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_prod_wh'), table_name='stock_movements')
    op.drop_index(op.f('ix_stocks_prod_wh_partner'), table_name='stocks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_stocks_prod_wh_partner'), 'stocks', ['product_id', 'warehouse_id', 'partner_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_prod_wh'), 'stock_movements', ['product_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_status_type'), 'requests', ['status', 'type'], unique=False)
    op.create_index(op.f('ix_requests_requester_id'), 'requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_requests_project_id'), 'requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_room_created'), 'messages', ['room_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_employee_documents_user_id'), 'employee_documents', ['user_id'], unique=False)
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_column('caisse_vouchers', 'validator_dg_id')
    op.drop_column('caisse_vouchers', 'validator_dga_id')
    op.drop_column('caisse_vouchers', 'validator_cg_id')
    op.drop_column('caisse_vouchers', 'demandeur_id')
    # ### end Alembic commands ###
