"""Add department_id to KPIProcessus

Revision ID: 7c5ca2ea3cdb
Revises: 8adc64a93174
Create Date: 2026-09-11 16:48:03.448574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5ca2ea3cdb'
down_revision: Union[str, Sequence[str], None] = '8adc64a93174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_assignments_position_key'), table_name='org_assignments')
    op.create_index(op.f('ix_org_assignments_position_key'), 'org_assignments', ['position_key'], unique=False)
    op.drop_constraint(op.f('org_assignments_employee_id_fkey'), 'org_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'org_assignments', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.add_column('quality_kpi_processus', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quality_kpi_processus', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quality_kpi_processus', type_='foreignkey')
    op.drop_column('quality_kpi_processus', 'department_id')
    op.drop_constraint(None, 'org_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('org_assignments_employee_id_fkey'), 'org_assignments', 'users', ['employee_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_org_assignments_position_key'), table_name='org_assignments')
    op.create_index(op.f('ix_org_assignments_position_key'), 'org_assignments', ['position_key'], unique=True)
    # ### end Alembic commands ###
