"""Add DGA and DG approval to requests

Revision ID: 9b72816f9a90
Revises: 72bcf84bad43
Create Date: 2026-09-14 12:40:06.102362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b72816f9a90'
down_revision: Union[str, Sequence[str], None] = '72bcf84bad43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE requeststatus ADD VALUE IF NOT EXISTS 'PENDING_DGA_APPROVAL'")
    op.execute("ALTER TYPE requeststatus ADD VALUE IF NOT EXISTS 'PENDING_DG_APPROVAL'")
    op.add_column('requests', sa.Column('dga_validator_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('dga_validated_at', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('dg_validator_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('dg_validated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'requests', 'users', ['dg_validator_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'users', ['dga_validator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'dg_validated_at')
    op.drop_column('requests', 'dg_validator_id')
    op.drop_column('requests', 'dga_validated_at')
    op.drop_column('requests', 'dga_validator_id')
    # ### end Alembic commands ###
