"""Add latitude and longitude to Project

Revision ID: bd11e93feaa8
Revises: 590a210938e8
Create Date: 2026-07-27 11:55:12.255784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd11e93feaa8'
down_revision: Union[str, Sequence[str], None] = '590a210938e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_requests_affaire_no'), table_name='fuel_requests')
    op.drop_index(op.f('ix_fuel_requests_dossier_no'), table_name='fuel_requests')
    op.drop_index(op.f('ix_fuel_requests_id'), table_name='fuel_requests')
    op.drop_index(op.f('ix_fuel_requests_vehicule_matricule'), table_name='fuel_requests')
    op.drop_table('fuel_requests')
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uq_purchase_orders_reference'), 'purchase_orders', type_='unique')
    op.create_index(op.f('ix_purchase_orders_reference'), 'purchase_orders', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_reference'), table_name='purchase_orders')
    op.create_unique_constraint(op.f('uq_purchase_orders_reference'), 'purchase_orders', ['reference'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    op.create_table('fuel_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('affaire_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dossier_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objet_deplacement', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicule_matricule', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('releve_kilometrique', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_jours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantite_carburant', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_LOGISTICS', 'PENDING_FINANCE', 'APPROVED', 'REJECTED', name='fuelrequeststatus'), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('logistics_validator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('logistics_validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finance_validator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finance_validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejection_comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fuel_requests_employee_id_fkey')),
    sa.ForeignKeyConstraint(['finance_validator_id'], ['users.id'], name=op.f('fuel_requests_finance_validator_id_fkey')),
    sa.ForeignKeyConstraint(['logistics_validator_id'], ['users.id'], name=op.f('fuel_requests_logistics_validator_id_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fuel_requests_manager_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fuel_requests_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fuel_requests_pkey'))
    )
    op.create_index(op.f('ix_fuel_requests_vehicule_matricule'), 'fuel_requests', ['vehicule_matricule'], unique=False)
    op.create_index(op.f('ix_fuel_requests_id'), 'fuel_requests', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_requests_dossier_no'), 'fuel_requests', ['dossier_no'], unique=False)
    op.create_index(op.f('ix_fuel_requests_affaire_no'), 'fuel_requests', ['affaire_no'], unique=False)
    # ### end Alembic commands ###
