"""Add KPI periodicity and permissions

Revision ID: d1da0115f4e3
Revises: 9b72816f9a90
Create Date: 2026-09-14 12:47:31.373554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1da0115f4e3'
down_revision: Union[str, Sequence[str], None] = '9b72816f9a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM('MONTHLY', 'QUARTERLY', 'SEMESTERLY', name='kpiperiodicity').create(op.get_bind())
    
    op.create_table('kpi_processus_editors',
    sa.Column('processus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['processus_id'], ['quality_kpi_processus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('processus_id', 'user_id')
    )
    op.add_column('quality_kpi_indicators', sa.Column('periodicity', sa.Enum('MONTHLY', 'QUARTERLY', 'SEMESTERLY', name='kpiperiodicity'), server_default='MONTHLY', nullable=False))
    op.add_column('quality_kpi_processus', sa.Column('editor_role_names', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quality_kpi_processus', 'editor_role_names')
    op.drop_column('quality_kpi_indicators', 'periodicity')
    op.drop_table('kpi_processus_editors')
    # ### end Alembic commands ###
