"""Add norm models

Revision ID: f326669cc67b
Revises: bd11e93feaa8
Create Date: 2026-07-27 15:13:44.416850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f326669cc67b'
down_revision: Union[str, Sequence[str], None] = 'bd11e93feaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('norm_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norm_categories_id'), 'norm_categories', ['id'], unique=False)
    op.create_index(op.f('ix_norm_categories_name'), 'norm_categories', ['name'], unique=False)
    op.create_table('norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['norm_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norms_code'), 'norms', ['code'], unique=True)
    op.create_index(op.f('ix_norms_id'), 'norms', ['id'], unique=False)
    op.create_index(op.f('ix_norms_title'), 'norms', ['title'], unique=False)
    op.create_table('norm_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norm_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['norm_id'], ['norms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norm_versions_id'), 'norm_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_norm_versions_id'), table_name='norm_versions')
    op.drop_table('norm_versions')
    op.drop_index(op.f('ix_norms_title'), table_name='norms')
    op.drop_index(op.f('ix_norms_id'), table_name='norms')
    op.drop_index(op.f('ix_norms_code'), table_name='norms')
    op.drop_table('norms')
    op.drop_index(op.f('ix_norm_categories_name'), table_name='norm_categories')
    op.drop_index(op.f('ix_norm_categories_id'), table_name='norm_categories')
    op.drop_table('norm_categories')
    # ### end Alembic commands ###
